# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
{{- $s3 := .Values.services.localstackS3 -}}
{{- if $s3.enabled }}

{{- if and $s3.persistence.enabled $s3.persistence.hostPath }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: localstack-s3-pv
  annotations:
    helm.sh/weight: "-30"
spec:
  capacity:
    storage: {{ $s3.persistence.size}}
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: {{ $s3.persistence.hostPath | quote }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    helm.sh/resource-policy: keep
    helm.sh/weight: "-30"
  name: localstack-s3-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ $s3.persistence.size }}
  volumeName: localstack-s3-pv
  storageClassName: ""
{{- else if $s3.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    helm.sh/resource-policy: keep
    helm.sh/weight: "-30"
  name: localstack-s3-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ $s3.persistence.size }}
  {{- with $s3.persistence.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
{{- end }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ $s3.serviceName }}
  labels:
    app: localstack-s3
  annotations:
    helm.sh/weight: "-30"
spec:
  {{ if $s3.enableNodePort }}
  type: NodePort
  {{ end }}
  ports:
  - port: {{ $s3.port }}
    {{ if $s3.enableNodePort }}
    nodePort: {{ $s3.nodePort }}
    {{ end }}
    targetPort: localstack-s3
    protocol: TCP
    name: http
  selector:
    app: localstack-s3

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack-s3
  labels:
    app: localstack-s3
  annotations:
    helm.sh/weight: "-30"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack-s3
  template:
    metadata:
      labels:
        app: localstack-s3
    spec:
      nodeSelector:
        {{- range $k, $v := .Values.global.nodeSelector}}
        {{ $k }}: {{ $v }}
        {{- end}}
        {{- range $k, $v := $s3.nodeSelector}}
        {{ $k }}: {{ $v }}
        {{- end}}
      containers:
      - name: localstack
        image: {{ $s3.image }}
        imagePullPolicy: IfNotPresent
        env:
        - name: SERVICES
          value: s3
        - name: DEBUG
          value: "1"
        - name: PERSIST_DEFAULT
          value: "0"
        - name: PERSIST_S3
          value: "1"
        - name: AWS_DEFAULT_REGION
          value: {{ $s3.region }}
        - name: LOCALSTACK_HOST
          value: "0.0.0.0"
        - name: EDGE_BIND_HOST
          value: "0.0.0.0"
        ports:
        - name: localstack-s3
          containerPort: {{ $s3.port }}
          protocol: TCP
        readinessProbe:
          tcpSocket: { port: {{ $s3.port }} }
          initialDelaySeconds: 3
          periodSeconds: 3
        livenessProbe:
          tcpSocket: { port: {{ $s3.port }} }
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          {{- toYaml ($s3.resources | default dict) | nindent 10 }}
        volumeMounts:
        {{- if $s3.persistence.enabled }}
        - name: data
          mountPath: /persisted-data
        {{- end }}
      volumes:
      {{- if $s3.persistence.enabled }}
      - name: data
        persistentVolumeClaim:
          claimName: localstack-s3-pvc
      {{- end }}


{{- if and $s3.enabled (not (empty $s3.buckets)) }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: localstack-s3-create-buckets
  annotations:
    "helm.sh/weight": "-30"
spec:
  ttlSecondsAfterFinished: 30
  backoffLimit: 6
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
      - name: wait-for-localstack-s3
        image: {{ $s3.bucketInitImage }}
        env:
        - name: AWS_ENDPOINT_URL
          value: http://{{ $s3.serviceName }}:{{ $s3.port }}
        - name: AWS_ACCESS_KEY_ID
          value: {{ $s3.accessKeyId }}
        - name: AWS_SECRET_ACCESS_KEY
          value: {{ $s3.accessKey }}
        - name: AWS_DEFAULT_REGION
          value: {{ $s3.region }}
        command:
        - sh
        - -c
        - |
          until aws s3 ls >/dev/null 2>&1; do
            echo "Waiting for localstack-s3..."
            sleep 2
          done
          echo "Localstack S3 is ready"
      containers:
      - name: aws-cli
        image: {{ $s3.bucketInitImage }}
        imagePullPolicy: IfNotPresent
        env:
        - name: AWS_ENDPOINT_URL
          value: http://{{ $s3.serviceName }}:{{ $s3.port }}
        - name: AWS_ACCESS_KEY_ID
          value: {{ $s3.accessKeyId }}
        - name: AWS_SECRET_ACCESS_KEY
          value: {{ $s3.accessKey }}
        - name: AWS_DEFAULT_REGION
          value: {{ $s3.region }}
        command: ["/bin/sh","-lc"]
        args:
        - |
          set -e

          echo "Creating buckets..."
          {{- range $b := $s3.buckets }}
          aws s3 mb s3://{{ $b }} || true
          {{- end }}

          echo "Setup complete!"
{{- end }}

{{- end }}
